controller: return detailed errors to agent (#1775)
## Summary of Changes
* When a device has known pathologies, like missing loopback interfaces,
return the details to the agent
* Today the controller returns a generic `<pubkey> not found` error,
which is not useful for contributors
* One or more of the following errors will now be returned:
    * "no or invalid VPNv4 loopback interface found for device"
    * "no or invalid IPv4 loopback interface found for device"
    * "VPNv4 loopback interface is unassigned (0.0.0.0)"
    * "IPv4 loopback interface is unassigned (0.0.0.0)"
    * "ISIS NET could not be generated"

Previously the agent would log:
```
2025/09/25 21:11:17.810726 dzclient.go:29: Error calling GetConfig: rpc error: code = NotFound desc = pubkey 9Lkn7hnX2pm4pLzyj4QoCi9Kd3oNkpZ35651Fcj5h71E not found 2025/09/25 21:11:17.810747 main.go:54: pollControllerAndConfigureDevice failed to call agent.GetConfigFromServer: "rpc error: code = NotFound desc = pubkey 9Lkn7hnX2pm4pLzyj4QoCi9Kd3oNkpZ35651Fcj5h71E not found" 2025/09/25 21:11:17.810755 main.go:131: ERROR: pollAndConfigureDevice returned rpc error: code = NotFound desc = pubkey 9Lkn7hnX2pm4pLzyj4QoCi9Kd3oNkpZ35651Fcj5h71E not found
```

Now the agent logs:
```
2025/09/27 19:01:57.524575 main.go:54: pollControllerAndConfigureDevice failed to call agent.GetConfigFromServer: "rpc error: code = FailedPrecondition desc = cannot render config for device 8scDVeZ8aB1TRTkBqaZgzxuk7WwpARdF1a39wYA7nR3W: [no or invalid IPv4 loopback interface found for device]"
2025/09/27 19:01:57.524582 main.go:131: ERROR: pollAndConfigureDevice returned rpc error: code = FailedPrecondition desc = cannot render config for device 8scDVeZ8aB1TRTkBqaZgzxuk7WwpARdF1a39wYA7nR3W: [no or invalid IPv4 loopback interface found for device]
```
* This change also stops the controller from logging errors and emitting
error metrics on these conditions.
## Testing Verification
* Unit test updates