qa: add support for env, client reuse (#1235)
## Summary of Changes
This PR does the following:
- Adds the ability to pass an environment of devnet, testnet or mainnet
- Refactors gRPC client handling to reuse client connections across
tests
- Adds a flag for force a multicast publisher instead of random
selection; necessary for troubleshooting a failed test

## Testing Verification

Test runs successfully using the devnet flag and forcing chi-dn-bm2 to
be a publisher:
```
➜  e2e git:(ss/qa_env) ✗ go test -v qa_test.go --args -hosts=chi-dn-bm2,chi-dn-bm3 -env devnet -force-publisher chi-dn-bm2
=== RUN   TestConnectivityUnicast
=== RUN   TestConnectivityUnicast/connect_ibrl_mode_from_chi-dn-bm2
=== RUN   TestConnectivityUnicast/connect_ibrl_mode_from_chi-dn-bm3
=== RUN   TestConnectivityUnicast/connectivity_check_from_chi-dn-bm2
=== RUN   TestConnectivityUnicast/connectivity_check_from_chi-dn-bm2/to_137.174.145.147
=== RUN   TestConnectivityUnicast/connectivity_check_from_chi-dn-bm3
=== RUN   TestConnectivityUnicast/connectivity_check_from_chi-dn-bm3/to_137.174.145.145
=== RUN   TestConnectivityUnicast/disconnect_from_chi-dn-bm2
=== RUN   TestConnectivityUnicast/disconnect_from_chi-dn-bm3
--- PASS: TestConnectivityUnicast (52.66s)
    --- PASS: TestConnectivityUnicast/connect_ibrl_mode_from_chi-dn-bm2 (22.49s)
    --- PASS: TestConnectivityUnicast/connect_ibrl_mode_from_chi-dn-bm3 (19.26s)
    --- PASS: TestConnectivityUnicast/connectivity_check_from_chi-dn-bm2 (4.34s)
        --- PASS: TestConnectivityUnicast/connectivity_check_from_chi-dn-bm2/to_137.174.145.147 (4.15s)
    --- PASS: TestConnectivityUnicast/connectivity_check_from_chi-dn-bm3 (4.26s)
        --- PASS: TestConnectivityUnicast/connectivity_check_from_chi-dn-bm3/to_137.174.145.145 (4.13s)
    --- PASS: TestConnectivityUnicast/disconnect_from_chi-dn-bm2 (1.24s)
    --- PASS: TestConnectivityUnicast/disconnect_from_chi-dn-bm3 (1.07s)
=== RUN   TestConnectivityMulticast
    qa_test.go:229: Using publisher: chi-dn-bm2, subscribers: [chi-dn-bm3], hosts: [chi-dn-bm2 chi-dn-bm3]
=== RUN   TestConnectivityMulticast/create_multicast_group
=== NAME  TestConnectivityMulticast
    qa_test.go:273: Multicast group created with pubkey: 2cTrgz3W5rLVXxJUD3H1zg8yDhDAAfSJZWRKWz92U4FS address: 233.84.178.1 owner: DZfHfcCXTLwgZeCRKQ1FL1UuwAwFAZM93g86NMYpfYan status: 1
=== RUN   TestConnectivityMulticast/update_multicast_allow_list
    qa_test.go:291: Multicast group qa-test-group added to allow list for publisher DZfHfcCXTLwgZeCRKQ1FL1UuwAwFAZM93g86NMYpfYan
    qa_test.go:303: Multicast group qa-test-group added to allow list for subscriber DZfHfcCXTLwgZeCRKQ1FL1UuwAwFAZM93g86NMYpfYan
=== RUN   TestConnectivityMulticast/connect_multicast_subscribers
=== RUN   TestConnectivityMulticast/connect_multicast_subscribers/subscribe_chi-dn-bm3
=== RUN   TestConnectivityMulticast/connect_multicast_publisher_chi-dn-bm2
=== RUN   TestConnectivityMulticast/check_multicast_subscribers
=== RUN   TestConnectivityMulticast/check_multicast_subscribers/check_subscriber_chi-dn-bm3
=== PAUSE TestConnectivityMulticast/check_multicast_subscribers/check_subscriber_chi-dn-bm3
=== CONT  TestConnectivityMulticast/check_multicast_subscribers/check_subscriber_chi-dn-bm3
    qa_test.go:396: Waiting for packets on subscriber chi-dn-bm3 for group 233.84.178.1
    qa_test.go:392: Subscriber chi-dn-bm3 received 25 packets for group 233.84.178.1
    qa_test.go:398: Waited 52.583125ms for packets on subscriber chi-dn-bm3 for group 233.84.178.1
=== RUN   TestConnectivityMulticast/stop_multicast_subscribers
=== RUN   TestConnectivityMulticast/stop_multicast_subscribers/stop_subscriber_chi-dn-bm3
=== RUN   TestConnectivityMulticast/disconnect_from_chi-dn-bm2
=== RUN   TestConnectivityMulticast/disconnect_from_chi-dn-bm3
=== RUN   TestConnectivityMulticast/delete_multicast_group
--- PASS: TestConnectivityMulticast (56.08s)
    --- PASS: TestConnectivityMulticast/create_multicast_group (0.99s)
    --- PASS: TestConnectivityMulticast/update_multicast_allow_list (1.99s)
    --- PASS: TestConnectivityMulticast/connect_multicast_subscribers (2.29s)
        --- PASS: TestConnectivityMulticast/connect_multicast_subscribers/subscribe_chi-dn-bm3 (2.29s)
    --- PASS: TestConnectivityMulticast/connect_multicast_publisher_chi-dn-bm2 (32.53s)
    --- PASS: TestConnectivityMulticast/check_multicast_subscribers (0.00s)
        --- PASS: TestConnectivityMulticast/check_multicast_subscribers/check_subscriber_chi-dn-bm3 (0.05s)
    --- PASS: TestConnectivityMulticast/stop_multicast_subscribers (0.04s)
        --- PASS: TestConnectivityMulticast/stop_multicast_subscribers/stop_subscriber_chi-dn-bm3 (0.04s)
    --- PASS: TestConnectivityMulticast/disconnect_from_chi-dn-bm2 (3.02s)
    --- PASS: TestConnectivityMulticast/disconnect_from_chi-dn-bm3 (2.83s)
    --- PASS: TestConnectivityMulticast/delete_multicast_group (1.23s)
PASS
ok      command-line-arguments  108.969s
```

Invalid env raises an error:
```
➜  e2e git:(ss/qa_env) go test -v qa_test.go --args -hosts=chi-dn-bm2,chi-dn-bm3 -env devnet123 -force-publisher chi-dn-bm2
2025/08/14 22:29:16 Invalid value for -env flag: "devnet123". Must be one of: devnet, testnet, mainnet
FAIL    command-line-arguments  0.231s
FAIL
```

Forced publisher not in host list raises an error:
```
➜  e2e git:(ss/qa_env) ✗ go test -v qa_test.go -run TestConnectivityMulticast --args -hosts=chi-dn-bm2,chi-dn-bm3 -env devnet -force-publisher chi-dn-bm4
=== RUN   TestConnectivityMulticast
    qa_test.go:219: Forced publisher chi-dn-bm4 is not in the host list: [chi-dn-bm2 chi-dn-bm3]
--- FAIL: TestConnectivityMulticast (0.00s)
FAIL
FAIL    command-line-arguments  0.233s
FAIL
```