qa: fix error handling (#1247)
## Summary of Changes
This cleans up some error handling in QA tests:
- properly passing stderr logs from the agent back to the caller;
otherwise, you need to fish in the agent logs
- exits early instead of progressing through unicast/multicast tests
during failure
- creates a pseudo-random multicast group name for testing as we still
allow groups with the same group code to be created which breaks the
test

## Testing Verification
Test fails early and stderr from agent gets populated in test results:
```
➜  doublezero git:(ss/qa_logging) ✗ go test -v e2e/qa_test.go --args -hosts=chi-dn-bm2,chi-dn-bm3 -env devnet                                                                                                                                                                                                                                                                                                             12:06:45 [766/1901]
=== RUN   TestConnectivityUnicast
=== RUN   TestConnectivityUnicast/connect_ibrl_mode_from_chi-dn-bm2
    qa_test.go:122:
                Error Trace:    /Users/fach/Documents/code/doublezero/e2e/qa_test.go:122
                Error:          Received unexpected error:
                                rpc error: code = Unknown desc = failed to connect unicast for client : command failed: exit status 1, output: Program Logs:
                                Program GYhQDKuESrasNZGyhMJhGYFtbzNijYhcrN9poSqCQVah invoke [1]
                                Program log: Instruction: CreateUser(user_type: IBRL, cyoa_type: GREOverDIA, client_ip: 137.174.145.145)
                                Program log: Device { account_type: Device, owner: DZfHfcCXTLwgZeCRKQ1FL1UuwAwFAZM93g86NMYpfYan, index: 307, bump_seed: 254, location_pk: 4LEqPVjEd6mDCrnsEz2xabcM8LxDRKmuRWkka2TaHZUW, exchange_pk: 9kq5va6NyviubLzfwdmLLnf5sw8Ba9tg5HfNYtUJp3xR, device_type: Switch, public_ip: 100.0.0.1, status: Activated, code: "chi-dn-dzd1", dz_prefixes: NetworkV4List([NetworkV4(Ipv4Network { addr: 10.251.2.0, p
refix: 24 })]), metrics_publisher_pk: DD9aRaAxpLRhwRVjFJ75Eqfi2xB8jn66kWVh9UZBwxxJ, contributor_pk: 9nTeydJeRv9abedUz7UiyzK3S2FoEsJJUSnjpr1U25FG, mgmt_vrf: "", interfaces: [V1(InterfaceV1 { status: Pending, name: "Loopback255", interface_type: Loopback, loopback_type: Vpnv4, vlan_id: 0, ip_net: NetworkV4(Ipv4Network { addr: 172.16.0.6, prefix: 32 }), node_segment_idx: 3, user_tunnel_endpoint: false }), V1(InterfaceV1 { status
: Pending, name: "Loopback256", interface_type: Loopback, loopback_type: Ipv4, vlan_id: 0, ip_net: NetworkV4(Ipv4Network { addr: 172.16.0.7, prefix: 32 }), node_segment_idx: 0, user_tunnel_endpoint: false }), V1(InterfaceV1 { status: Pending, name: "Switch1/11/2", interface_type: Physical, loopback_type: None, vlan_id: 0, ip_net: NetworkV4(Ipv4Network { addr: 172.16.0.12, prefix: 31 }), node_segment_idx: 0, user_tunnel_endpoi
nt: false }), V1(InterfaceV1 { status: Pending, name: "Switch1/11/4", interface_type: Physical, loopback_type: None, vlan_id: 0, ip_net: NetworkV4(Ipv4Network { addr: 172.16.0.14, prefix: 31 }), node_segment_idx: 0, user_tunnel_endpoint: false })], reference_count: 2, users_count: 0, max_users: 0 }
                                Program GYhQDKuESrasNZGyhMJhGYFtbzNijYhcrN9poSqCQVah consumed 97341 of 200000 compute units
                                Program GYhQDKuESrasNZGyhMJhGYFtbzNijYhcrN9poSqCQVah failed: custom program error: 0x14
                                Error: Error creating user
                Test:           TestConnectivityUnicast/connect_ibrl_mode_from_chi-dn-bm2
                Messages:       ConnectUnicast failed
=== NAME  TestConnectivityUnicast
    qa_test.go:128: Failed to connect IBRL mode from host chi-dn-bm2
=== RUN   TestConnectivityUnicast/disconnect_from_chi-dn-bm2
=== RUN   TestConnectivityUnicast/disconnect_from_chi-dn-bm3
--- FAIL: TestConnectivityUnicast (1.61s)
    --- FAIL: TestConnectivityUnicast/connect_ibrl_mode_from_chi-dn-bm2 (0.85s)
    --- PASS: TestConnectivityUnicast/disconnect_from_chi-dn-bm2 (0.34s)
    --- PASS: TestConnectivityUnicast/disconnect_from_chi-dn-bm3 (0.42s)
=== RUN   TestConnectivityMulticast
    qa_test.go:236: Using publisher: chi-dn-bm2, subscribers: [chi-dn-bm3], hosts: [chi-dn-bm2 chi-dn-bm3]
=== RUN   TestConnectivityMulticast/create_multicast_group
=== NAME  TestConnectivityMulticast
    qa_test.go:282: Multicast group created with pubkey: XhLXw57CGMQWsrsK7u7tNPL9zyfJ3NozJ4G8ad7C4ZJ address: 233.84.178.2 owner: DZfHfcCXTLwgZeCRKQ1FL1UuwAwFAZM93g86NMYpfYan status: 1
=== RUN   TestConnectivityMulticast/update_multicast_allow_list
    qa_test.go:296:
                Error Trace:    /Users/fach/Documents/code/doublezero/e2e/qa_test.go:296
                Error:          Received unexpected error:
                                rpc error: code = Unknown desc = command failed: exit status 1, output: Error: Publisher is already in the allowlist
                Test:           TestConnectivityMulticast/update_multicast_allow_list
                Messages:       MulticastAllowListAdd failed
=== NAME  TestConnectivityMulticast
    qa_test.go:314: Failed to update multicast allow list
=== RUN   TestConnectivityMulticast/disconnect_from_chi-dn-bm2
=== RUN   TestConnectivityMulticast/disconnect_from_chi-dn-bm3
=== RUN   TestConnectivityMulticast/delete_multicast_group
--- FAIL: TestConnectivityMulticast (3.07s)
    --- PASS: TestConnectivityMulticast/create_multicast_group (0.99s)
    --- FAIL: TestConnectivityMulticast/update_multicast_allow_list (0.26s)
    --- PASS: TestConnectivityMulticast/disconnect_from_chi-dn-bm2 (0.33s)
    --- PASS: TestConnectivityMulticast/disconnect_from_chi-dn-bm3 (0.22s)
    --- PASS: TestConnectivityMulticast/delete_multicast_group (1.14s)
FAIL
FAIL    command-line-arguments  4.919s
FAIL
```